# Site settings
title: KNOSSOS &mdash; 3D Image Annotation
name: KNOSSOS
email: knossosteam@gmail.com
description: >
  KNOSSOS is a scientific application for 3D image data annotation.
baseurl: ""
url: "https://knossos.app"
github_username:  knossos-project

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true
  # auto_ids: false

sass:
  style: :compressed

include:
 - _images
 - _sources
 - _static

exclude:
  - "feed.xml"
  - "Makefile"