# Site settings
title: KNOSSOS
name: KNOSSOS
email: knossosteam@gmail.com
description: >
  KNOSSOS is a scientific application for 3D image data annotation.
baseurl: ""
url: "https://knossos.app"
github_username:  knossos-project

# Build settings
theme: just-the-docs
kramdown:
  parse_block_html: true

aux_links:
  "KNOSSOS on GitHub":
    - "https://github.com/knossos-project/knossos"
nav_external_links:
  - title: Home
    url: /
    hide_icon: true

callouts_level: quiet
callouts:
  note:
    title: Note
    color: blue
